# Generated by Django 5.0.6 on 2024-06-09 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='prix',
            field=models.IntegerField(default=0),
        ),
    ]
